
# Version 2 - For SOLR and Muscat 3
# Note: the default store type is TEXT
# WHich means it is tokenized
# For facets and untokenized filtering
# use string (or integer)

config:
    :version: 2.0
    :model: source

fields:  
  "001":
  "008_date1":
      :from_tag: 008
      :index_helper: :marc_helper_get_008_date1
  "008_date2":
      :from_tag: 008
      :index_helper: :marc_helper_get_008_date2
  "008_language":
      :from_tag: 008
      :index_helper: :marc_helper_get_008_language
  "028a":
  "028b":
  "031d":
  "031e":
  "031m":
  "031p":
      :store: true
  "pae_complete":
       :store: true
       :as: pae
       :from_tag: "031"
       :index_processor_helper: :marc_create_pae_entry
  "031q":
  "031t_filter":
      :type: string
      :from_tag: "031"
      :from_subtag: "t"
  "031t":
  "033a":
  "035a":
  "041a":
  "041e":
  "041h":
  "100a":
#      :missing_helper: marc_helper_set_anonymous
  "100d":
  "110a":
  "110b":
  "130a":
      :store: true
      :type: string
  "130k":
  "130m":
  "130n":
      :store: true
  "130o":
  "130p":
  "130r":
  "240a":
  "240a_filter":
      :store: true
      :type: string
      :from_tag: "240"
      :from_subtag: "a"
  "240k":
  "240m":
  "240m_filter":
      :type: string
      :from_tag: "240"
      :from_subtag: "m"
  "240n":
      :store: true
  "240o":
  "240p":
  "240r":
      :store: true
  "245a":
  "245b":
  "245c":
  "246a":
  "246i":
  "254a":
  "260a":
  "260b":
  "260c":
  "260c_year":
       :type: integer
       :store: true
       :from_tag: "260"
       :from_subtag: "c"
       :index_processor_helper: :marc_extract_dates
  "260e":
  "260f":
  "270a":
  "300a":
  "300b":
  "300c":
  "340d":
  "351a":
  "383b":
  "500a":
  "5005":
  "505a":
  "506a":
  "508a":
  "510a":
  "510c":
  "511a":
  "518a":
  "520a":
  "525a":
  "533a":
  "541a":
  "541c":
  "541d":
  "545a":
  "546a":
  "555a":
  "561a":
  "5615":
  "562a":
  "5625":
  "563a":
  "5635":
  "590a":
  "590b":
  "591a":
  "592a":
  "593a":
      :store: true
  "593a_filter":
      :type: string
      :from_tag: "593"
      :from_subtag: "a"
  "594a":
  "594b":
      :store: true
      :type: string
  "594c":
  "594d":
  "594e":
  "594f":
  "594g":
  "594h":
  "594i":
  "594k":
  "594l":
  "594m":
  "594n":
  "595a":
  "595u":
  "596a":
  "597a":
  "598a":
  "599a":
  "650a":
  "651a":
  "657a":
  "690a":
  "650a_filter":
      :type: string
      :from_tag: "650"
      :from_subtag: "a"
  "690n":
  "691n":
  "700a":
  "700d":
  "700e":
  "700t":
  "7004":
  "7005":
  "710a":
  "710b":
  "710k":
  "710e":
  "7104":
  "7105":
  "730a":
  "730a_filter":
      :type: string
      :from_tag: "730"
      :from_subtag: "a"
  "730k":
  "730m":
  "730n":
  "730o":
  "730p":
  "730r":
  "740a":
  "752a":
  "752d":
  "773w":
  "774w":
  "786a":
  "786d":
  "786i":
  "786o":
  "786t":
  "787a":
  "787n":
  "787w":
  "852a_facet":
      :type: text ## hack for sunspot: make this field work as fulltext
      :from_tag: "852"
      :from_subtag: "a"
      :as: "852a_facet_sm" # But set it manually as string multiple
      :holding_record: true
  "852a":
      :holding_record: true
  "852b":
      :holding_record: true
  "852c":
      :store: true
      :holding_record: true
  "852d":
      :holding_record: true
  "852e":
      :holding_record: true
  "852q":
      :holding_record: true
  "852z":
      :holding_record: true
  "856u":
  "856x":
      :type: string
  "856z":
  "740_autocomplete":
      :index_processor_helper: marc_create_aggregated_text
      :tags:
          :740: "a"
          :730: "a"
          :240: "a"
          :130: "a"
      :store: true
      :type: string
