--- !map:Settings 
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"300": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - b
    - - c
"500": 
  layout: 
    fields: 
    - - a
      - growfield: true
"518": 
  layout: 
    fields: 
    - - a
      - values: 
        - "Composition date: "
        - "First performance date: "
        - "Performance date: "
        editor_partial: subfield_autocomplete
"541": 
  layout: 
    fields: 
    - - c
      - growfield: true
    - - a
    - - d
    - - e
"563": 
  new_window: sources
  layout: 
    fields: 
    - - a
      - growfield: true
    - - u
      - type: source
        editor_partial: subfield_secondary
        only_new_window: true
"592": 
  layout: 
    fields: 
    - - a
"651":
  new_window: places
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: place
        editor_partial: subfield_secondary
        allow_new: true
"691":
  new_window: catalogues
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: catalogue
        editor_partial: subfield_secondary
        allow_new: false
    - - n
"700":
  new_window: people
  new_window_field: full_name_equals
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - j
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
    relator_codes: 
      - fmo
      - scr
      - cmp
      - arr
      - prf
      - dte
      - lyr
      - lbt
      - trl
      - pbl
      - prt
      - edt
      - ltg
      - egr
      - ill
      - aut
      - oth
      - dub
      - ctb
"710":
  new_window: institutions
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: institution
        editor_partial: subfield_secondary
        allow_new: true
    - - b
    - - g
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
    relator_codes: 
      - pbl
      - fmo
      - dpt
      - dte
      - scr
      - prf
      - prt
      - edt
      - asn
      - oth
"852": 
  allow_new: true
  new_window: institutions
  layout: 
    fields: 
    - - a
      - type: library
        editor_partial: subfield_secondary
    - - b
    - - z
    - - q
    - - c
      - growfield: true
    - - d
"856": 
  layout: 
    fields: 
    - - u
    - - z
    - - x
      - values: 
        - "IIIF"
        editor_partial: subfield_select
ui: 
  hide_marc_identifiers: true
