--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"008": 
  tag: tag_no_subfield
  tag_params: 
    maskedinput: 
      definitions: "['~']='[|0-9]'"
      mask: 999999a~~~~~~~~||||||||||||||||||||aaa|d
  tag_header: none
"024": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - "2"
      - values: 
        - "BNE"
        - "BNF"
        - "DNB"
        - "ICCU"
        - "ISNI"
        - "LC"
        - "NLP"
        - "NKC"
        - "SWNL"
        - "VIAF"
        - "WKP"
        default: "VIAF"
        editor_partial: subfield_select
      - cols: 2
    columns: 4

"040": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - c
      - cols: 2
    - - d
      - cols: 2
    - - b
      - cols: 2
    columns: 4
"042": 
  layout: 
    fields: 
    - - a
      - cols: 4
        values:
        - "individualized" 
        - "not individualized"
        editor_partial: subfield_select
    columns: 4
"043": 
  layout: 
    fields: 
    - - c
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Country"
    columns: 2
  tag_params:
    codes:
      - "XC-DZ"
      - "XD-AR"
      - "XB-AM"
      - "XE-AU"
      - "XA-AT"
      - "XA-AT-2"
      - "XA-AT-3"
      - "XA-AT-5"
      - "XA-AT-6"
      - "XA-AT-7"
      - "XA-AT-4"
      - "XA-AT-9"
      - "XA-BE"
      - "XC-BJ"
      - "XD-BR"
      - "XA-BG"
      - "XB-KH"
      - "XD-CA"
      - "XD-CL"
      - "XB-CN"
      - "XD-CO"
      - "XA-HR"
      - "XD-CU"
      - "XA-CZ"
      - "XA-DK"
      - "XC-EG"
      - "XA-EE"
      - "XA-FI"
      - "XA-FR"
      - "XA-DE"
      - "XA-DE-BY"
      - "XA-DE-SN"
      - "XA-GR"
      - "XA-VA"
      - "XD-HN"
      - "XA-HU"
      - "XA-IS"
      - "XB-IN"
      - "XB-IR"
      - "XA-IE"
      - "XB-IL"
      - "XA-IT-32"
      - "XA-IT"
      - "XB-JP"
      - "XB-KR"
      - "XA-LV"
      - "XA-LT"
      - "XA-LU"
      - "XA-MT"
      - "XD-MX"
      - "XA-ME"
      - "XA-NL"
      - "XE-NZ"
      - "XA-NO"
      - "XD-PY"
      - "XA-PL"
      - "XA-PT"
      - "XD-PR"
      - "XA-RO"
      - "XA-RU"
      - "XA-RS"
      - "XA-SK"
      - "XA-SI"
      - "XC-ZA"
      - "XA-ES"
      - "XA-SE"
      - "XA-CH"
      - "XA-CH-VD"
      - "XB-SY"
      - "XD-TT"
      - "XB-TR"
      - "XA-UA"
      - "XA-GB"
      - "XD-US"
      - "XD-UY"
      - "XD-VE"
"100": 
  layout: 
    fields: 
    - - a
      - cols: 2
        trigger:
        - save:
          - referring_sources
    - - c
      - cols: 2
    - - d
      - cols: 2
    - - w
      - cols: 2
    - - y
      - cols: 2
    columns: 4
"375": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Gender"
    columns: 2
  tag_params:
    codes:
      - male
      - female
      - "unknown"
"400": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - d
      - cols: 2
    - - j
      - cols: 2
        editor_partial: subfield_select_codes
        select_label: "Type of Variant"
    columns: 2
  tag_params:
    codes:
      - "bn"
      - "da"
      - "do"
      - "dv"
      - "ee"
      - "ef"
      - "ff"
      - "gg"
      - "in"
      - "mo"
      - "tn"
      - "ub"
      - "z"
      - "xx"
    columns: 4
"500": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - "a"
      - type: person
        editor_partial: subfield_secondary
      - cols: 4
    - - "i"
      - cols: 2
        editor_partial: subfield_select_codes
        select_label: "Relationship"
    columns: 4
  tag_params:
    codes:
      - brother of
      - child of
      - mother of
      - confused with
      - sister of
      - married with
      - father of
      - related to
      - other
"510": 
  allow_new: true
  new_window: institutions
  layout: 
    fields: 
    - - "a"
      - type: library
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4
"549": 
  layout: 
    fields: 
    - - a
      - cols: 2
    columns: 2
"550": 
  layout: 
    fields: 
    - - a
      - cols: 2
    columns: 2
"551": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - i
      - cols: 2
        editor_partial: subfield_select_codes
        select_label: "Type"
    columns: 2
  tag_params:
    codes:
      - go
      - ha
      - po
      - so
      - wl
      - wo
      - wr
"599": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - b
      - cols: 2
    columns: 4
"667": 
  layout: 
    fields: 
    - - a
      - cols: 2
    columns: 2
"670": 
  allow_new: true
  new_window: catalogues
  layout: 
    fields: 
    - - "a"
      - type: catalogue
        editor_partial: subfield_secondary
      - cols: 4
    - - "b"
      - cols: 2
    columns: 4
"678": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - b
      - cols: 2
    - - u
      - cols: 4
    columns: 4
"680": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - i
      - cols: 2
    - - "5"
      - cols: 4
    columns: 4
"856": 
  layout: 
    fields: 
    - - u
      - cols: 2
        unrestricted:
          - person_restricted
    - - y
      - cols: 2
        unrestricted:
          - person_restricted
    columns: 4
