--- !map:Settings
server:
  - validate_user_abilities
client:
  "100": 
    tags:
      "0": required
      a: required
  "240":
    tag_overrides:
      exclude:
        m:
        - collection
        - theoretica_source
        - libretto_edition 
        - composite_volume
    tags:
      "0": mandatory
      m: required, warning
  "245": 
    tags:
      a: mandatory
  "260":
    tag_overrides:
      exclude:
        "c":
        - composite_volume
    tags:
      c: required
  "300": 
    tag_overrides:
      exclude:
        "a":
        - composite_volume
    tags:
      a: required
  "588":
    tag_overrides:
      exclude:
        "a":
        - collection
        - composite_volume
        - edition_content
        - source
        - libretto_source
        - theoretica_source
        - libretto_edition_content
        - theoretica_edition_content
    tags:
      "a": mandatory
  "593":
    tag_overrides:
      exclude:
        "a":
        - collection
        - composite_volume
    tags:
      "a": mandatory
  "594": 
    tag_overrides:
      exclude:
        "b":
        - composite_volume
    tags:
      b: required
  "650":
    tag_overrides:
      exclude:
        "0":
        - collection
        - composite_volume
    tags:
      "0": mandatory
  "700": 
    tags:
      "0": required
      "4":
        required_if:
          "700": "0"
  "710": 
    tags:
      "0": required
      "4":
        required_if:
          "710": "0"
  "730":
    tags:
      "0": required
  "787": 
    tags:
      "n": required
      "w": required
      "4": required
  "852":
    tag_overrides:
      exclude:
        "x":
        - edition
        - edition_content
        - libretto_edition
        - libretto_edition_content
        - theoretica_edition
        - theoretica_edition_content
    tags:
      c: required, warning
      x: mandatory
  "856": 
    tags:
      u:
        begins_with: "http"
      z:
        required_if:
          "856": "u"
      x:
        required_if:
          "856": "u"
